#!/bin/bash

echo 'cloning Workspace'
echo 'folder: ~/plattform-ros'
echo 'source: https://github.com/HMlabh/plattform-ros'

if [ -d ~/plattform-ros ]
  then
    echo 'ERROR: Folder existing'
  else
    git clone https://github.com/HMlabh/plattform-ros ~/plattform-ros
    echo 'cloning complete'
fi
 


exit 0
