#!/bin/bash

echo -e "\e[34mupdating Workspace\e[0m"
echo -e "\e[34mfolder: ~/plattform-ros\e[0m"
echo -e "\e[34msource: https://github.com/HMlabh/plattform-ros\e[0m"

if [ -d ~/plattform-ros ]
  then
    cd ~/plattform-ros
    
    echo "deleting changes"
    git add *
    git stash
    git stash drop

    echo "pulling..."
    git pull

    
    echo -e "\e[32mupdate complete\e[0m"
  else
    echo -e "\e[31mERROR Folder not existing\e[0m"
fi
 


exit 0
