#!/bin/bash

echo -e "\e[34mupdating Workspace\e[0m"
echo -e "\e[34mfolder: ~/plattform-ros\e[0m"
echo -e "\e[34msource: https://github.com/HMlabh/plattform-ros\e[0m"

#################git##################
if [ -d ~/plattform-ros ]
  then
    cd ~/plattform-ros
    
    echo -e "\e[34mdeleting changes\e[0m"
    git add *
    git stash
    git stash drop

    echo -e "\e[34mpulling...\e[0m"
    git pull

    
    echo -e "\e[32mupdate complete\e[0m"
  else
    echo -e "\e[31mERROR Folder not existing\e[0m"
fi

################ ros ###################
echo -e "\e[34msourcing Setup.bash\e[0m"
source ~/plattform-ros/devel/setup.bash

echo -e "\e[34mcompiling...\e[0m"
cd ~/plattform-ros
catkin_make

exit 0
